# -*- coding: utf-8 -*-
"""TASK 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aXEjfzp0KUysl_wbhGZYYfUp9LxIlhhV

1 - Write a program which takes a number as input from the user and check whether the number is odd or even.If odd print the number is odd if not print it is even.
"""

#please enter your answer below this line
num = int(input("Enter the Number"))
if num%2== 1:
   print("The Number is Odd")

"""2 -Write a program to find the largest among three numbers and print the largest number."""

#please enter your answer below this line
num1=float(input("Enter the First Number"))
num2=float(input("Enter the Second Number"))
num3=float(input("Enter the Third Number"))
if (num1>num2 and num1>number3):
  print("The Largest number is :",num1)
elif(num2>num1 and num2>num3):
  print("The Largest Number is :",num2)
else:
  print("The Largest Number is:",num3)

"""3 -Write a function to prompt for a score between 0.0 and 1.0.

    If the score is out of range, print an error.
    If the score is between 0.0 and 1.0, print a grade using the following table:
    Score Grade
             Score	Grade
            >= 0.9	A
            >= 0.8	B
            >= 0.7	C
            >= 0.6	D
             < 0.6	F
If the user enters a value out of range, print a suitable error message and exit. For the test, enter a score of 0.85.
"""

#please enter your answer below this line
score = float(input("Enter the score"))
if score <0.6:
  print("Grade F")
elif score>=0.6 and score<0.7:
  print("Grade D")
elif score>=0.7 and score<0.8:
  print("Grade C")
elif score>=0.8 and score<0.9:
  print("Grade B")
elif score>=0.9 and score<1.0:
  print("Grade A")
else:
  print("Error")